# Generated by Django 2.2.5 on 2019-09-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
