# Generated by Django 2.2.5 on 2019-09-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190927_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(blank=True, default='tmp', max_length=200, null=True),
        ),
    ]
