# Generated by Django 2.2.5 on 2019-09-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='luis-rocha-yM_mQIl5Vks-unsplash.jpg', null=True, upload_to=''),
        ),
    ]
